In [6]:
import pandas as pd
import glob
pd.set_option('display.max_columns', None)

In [7]:
#extract file names
path = "Statsbomb/data/matches/"

competition_id = 11

path_to_json = path + str(competition_id)

file_list = glob.glob(path_to_json + "/*.json")

print(file_list)

['Statsbomb/data/matches/11/41.json', 'Statsbomb/data/matches/11/40.json', 'Statsbomb/data/matches/11/37.json', 'Statsbomb/data/matches/11/21.json', 'Statsbomb/data/matches/11/26.json', 'Statsbomb/data/matches/11/27.json', 'Statsbomb/data/matches/11/1.json', 'Statsbomb/data/matches/11/2.json', 'Statsbomb/data/matches/11/24.json', 'Statsbomb/data/matches/11/25.json', 'Statsbomb/data/matches/11/22.json', 'Statsbomb/data/matches/11/38.json', 'Statsbomb/data/matches/11/4.json', 'Statsbomb/data/matches/11/42.json', 'Statsbomb/data/matches/11/39.json', 'Statsbomb/data/matches/11/23.json']

In [8]:
#create pandas dataframes from the json files
dfs = []

for file in file_list:
    data = pd.read_json(file)
    dfs.append(data)
    

combined = pd.concat(dfs, ignore_index=True)

In [9]:
combined['match_id'].count()

485

In [10]:
match_ids = combined["match_id"].to_list()

In [11]:
len(match_ids)

485

In [12]:
#extract event data according to match_id
path_to_events_json = "Statsbomb/data/events/"

event_lists = []

_list = glob.glob(path_to_events_json + "*.json")

for x in _list:
    for i in range(len(match_ids)):
        if x == path_to_events_json + str(match_ids[i]) + ".json":
            event_lists.append(x)

In [13]:
print(event_lists)
print(len(event_lists))

['Statsbomb/data/events/265958.json', 'Statsbomb/data/events/69182.json', 'Statsbomb/data/events/303696.json', 'Statsbomb/data/events/69244.json', 'Statsbomb/data/events/266620.json', 'Statsbomb/data/events/69213.json', 'Statsbomb/data/events/69340.json', 'Statsbomb/data/events/266724.json', 'Statsbomb/data/events/303680.json', 'Statsbomb/data/events/9855.json', 'Statsbomb/data/events/69252.json', 'Statsbomb/data/events/70264.json', 'Statsbomb/data/events/68341.json', 'Statsbomb/data/events/9592.json', 'Statsbomb/data/events/69229.json', 'Statsbomb/data/events/16231.json', 'Statsbomb/data/events/69157.json', 'Statsbomb/data/events/68316.json', 'Statsbomb/data/events/16289.json', 'Statsbomb/data/events/267660.json', 'Statsbomb/data/events/69291.json', 'Statsbomb/data/events/70225.json', 'Statsbomb/data/events/69141.json', 'Statsbomb/data/events/9880.json', 'Statsbomb/data/events/69268.json', 'Statsbomb/data/events/69287.json', 'Statsbomb/data/events/9642.json', 'Statsbomb/data/events/70272.json', 'Statsbomb/data/events/265866.json', 'Statsbomb/data/events/266525.json', 'Statsbomb/data/events/267343.json', 'Statsbomb/data/events/69248.json', 'Statsbomb/data/events/68320.json', 'Statsbomb/data/events/16196.json', 'Statsbomb/data/events/267085.json', 'Statsbomb/data/events/267590.json', 'Statsbomb/data/events/15978.json', 'Statsbomb/data/events/266440.json', 'Statsbomb/data/events/267197.json', 'Statsbomb/data/events/303634.json', 'Statsbomb/data/events/69209.json', 'Statsbomb/data/events/68361.json', 'Statsbomb/data/events/70301.json', 'Statsbomb/data/events/266952.json', 'Statsbomb/data/events/267569.json', 'Statsbomb/data/events/69177.json', 'Statsbomb/data/events/68336.json', 'Statsbomb/data/events/266883.json', 'Statsbomb/data/events/69225.json', 'Statsbomb/data/events/266929.json', 'Statsbomb/data/events/70287.json', 'Statsbomb/data/events/69272.json', 'Statsbomb/data/events/69337.json', 'Statsbomb/data/events/267400.json', 'Statsbomb/data/events/69264.json', 'Statsbomb/data/events/16010.json', 'Statsbomb/data/events/69233.json', 'Statsbomb/data/events/70291.json', 'Statsbomb/data/events/69232.json', 'Statsbomb/data/events/266528.json', 'Statsbomb/data/events/69265.json', 'Statsbomb/data/events/69320.json', 'Statsbomb/data/events/266986.json', 'Statsbomb/data/events/69273.json', 'Statsbomb/data/events/69336.json', 'Statsbomb/data/events/70286.json', 'Statsbomb/data/events/69224.json', 'Statsbomb/data/events/267138.json', 'Statsbomb/data/events/69176.json', 'Statsbomb/data/events/303377.json', 'Statsbomb/data/events/68360.json', 'Statsbomb/data/events/70300.json', 'Statsbomb/data/events/266142.json', 'Statsbomb/data/events/9726.json', 'Statsbomb/data/events/68321.json', 'Statsbomb/data/events/69160.json', 'Statsbomb/data/events/303731.json', 'Statsbomb/data/events/303674.json', 'Statsbomb/data/events/69249.json', 'Statsbomb/data/events/70273.json', 'Statsbomb/data/events/68356.json', 'Statsbomb/data/events/266066.json', 'Statsbomb/data/events/69269.json', 'Statsbomb/data/events/69286.json', 'Statsbomb/data/events/70224.json', 'Statsbomb/data/events/265830.json', 'Statsbomb/data/events/266420.json', 'Statsbomb/data/events/303707.json', 'Statsbomb/data/events/265963.json', 'Statsbomb/data/events/9602.json', 'Statsbomb/data/events/69156.json', 'Statsbomb/data/events/68317.json', 'Statsbomb/data/events/266477.json', 'Statsbomb/data/events/69228.json', 'Statsbomb/data/events/303615.json', 'Statsbomb/data/events/266498.json', 'Statsbomb/data/events/303479.json', 'Statsbomb/data/events/68340.json', 'Statsbomb/data/events/69316.json', 'Statsbomb/data/events/69253.json', 'Statsbomb/data/events/69195.json', 'Statsbomb/data/events/266230.json', 'Statsbomb/data/events/267533.json', 'Statsbomb/data/events/267499.json', 'Statsbomb/data/events/265918.json', 'Statsbomb/data/events/69212.json', 'Statsbomb/data/events/69300.json', 'Statsbomb/data/events/69245.json', 'Statsbomb/data/events/69183.json', 'Statsbomb/data/events/16190.json', 'Statsbomb/data/events/68326.json', 'Statsbomb/data/events/265952.json', 'Statsbomb/data/events/267596.json', 'Statsbomb/data/events/9799.json', 'Statsbomb/data/events/69219.json', 'Statsbomb/data/events/266846.json', 'Statsbomb/data/events/267611.json', 'Statsbomb/data/events/267492.json', 'Statsbomb/data/events/70307.json', 'Statsbomb/data/events/16240.json', 'Statsbomb/data/events/68330.json', 'Statsbomb/data/events/69171.json', 'Statsbomb/data/events/265944.json', 'Statsbomb/data/events/69223.json', 'Statsbomb/data/events/266885.json', 'Statsbomb/data/events/266240.json', 'Statsbomb/data/events/70281.json', 'Statsbomb/data/events/69274.json', 'Statsbomb/data/events/69331.json', 'Statsbomb/data/events/9609.json', 'Statsbomb/data/events/69262.json', 'Statsbomb/data/events/69327.json', 'Statsbomb/data/events/266201.json', 'Statsbomb/data/events/69235.json', 'Statsbomb/data/events/266256.json', 'Statsbomb/data/events/70297.json', 'Statsbomb/data/events/267502.json', 'Statsbomb/data/events/69184.json', 'Statsbomb/data/events/16173.json', 'Statsbomb/data/events/69307.json', 'Statsbomb/data/events/69242.json', 'Statsbomb/data/events/266299.json', 'Statsbomb/data/events/69215.json', 'Statsbomb/data/events/303517.json', 'Statsbomb/data/events/266149.json', 'Statsbomb/data/events/267076.json', 'Statsbomb/data/events/70219.json', 'Statsbomb/data/events/9783.json', 'Statsbomb/data/events/69254.json', 'Statsbomb/data/events/70262.json', 'Statsbomb/data/events/9717.json', 'Statsbomb/data/events/68347.json', 'Statsbomb/data/events/16149.json', 'Statsbomb/data/events/69151.json', 'Statsbomb/data/events/69278.json', 'Statsbomb/data/events/267373.json', 'Statsbomb/data/events/303700.json', 'Statsbomb/data/events/69297.json', 'Statsbomb/data/events/70223.json', 'Statsbomb/data/events/69147.json', 'Statsbomb/data/events/265837.json', 'Statsbomb/data/events/267670.json', 'Statsbomb/data/events/267220.json', 'Statsbomb/data/events/266827.json', 'Statsbomb/data/events/68351.json', 'Statsbomb/data/events/303487.json', 'Statsbomb/data/events/69239.json', 'Statsbomb/data/events/266467.json', 'Statsbomb/data/events/69238.json', 'Statsbomb/data/events/266871.json', 'Statsbomb/data/events/16109.json', 'Statsbomb/data/events/70275.json', 'Statsbomb/data/events/68350.json', 'Statsbomb/data/events/9700.json', 'Statsbomb/data/events/303652.json', 'Statsbomb/data/events/69280.json', 'Statsbomb/data/events/69146.json', 'Statsbomb/data/events/69279.json', 'Statsbomb/data/events/69296.json', 'Statsbomb/data/events/70263.json', 'Statsbomb/data/events/69255.json', 'Statsbomb/data/events/266236.json', 'Statsbomb/data/events/267077.json', 'Statsbomb/data/events/266148.json', 'Statsbomb/data/events/303516.json', 'Statsbomb/data/events/266631.json', 'Statsbomb/data/events/15973.json', 'Statsbomb/data/events/69214.json', 'Statsbomb/data/events/70259.json', 'Statsbomb/data/events/69306.json', 'Statsbomb/data/events/69243.json', 'Statsbomb/data/events/69185.json', 'Statsbomb/data/events/9794.json', 'Statsbomb/data/events/266670.json', 'Statsbomb/data/events/70296.json', 'Statsbomb/data/events/266892.json', 'Statsbomb/data/events/69234.json', 'Statsbomb/data/events/266191.json', 'Statsbomb/data/events/69263.json', 'Statsbomb/data/events/69326.json', 'Statsbomb/data/events/267368.json', 'Statsbomb/data/events/69275.json', 'Statsbomb/data/events/69330.json', 'Statsbomb/data/events/303473.json', 'Statsbomb/data/events/265894.json', 'Statsbomb/data/events/70280.json', 'Statsbomb/data/events/16056.json', 'Statsbomb/data/events/69222.json', 'Statsbomb/data/events/68331.json', 'Statsbomb/data/events/69170.json', 'Statsbomb/data/events/266406.json', 'Statsbomb/data/events/266056.json', 'Statsbomb/data/events/69259.json', 'Statsbomb/data/events/303664.json', 'Statsbomb/data/events/70306.json', 'Statsbomb/data/events/9736.json', 'Statsbomb/data/events/265857.json', 'Statsbomb/data/events/68366.json', 'Statsbomb/data/events/9673.json', 'Statsbomb/data/events/16095.json', 'Statsbomb/data/events/15986.json', 'Statsbomb/data/events/69218.json', 'Statsbomb/data/events/69166.json', 'Statsbomb/data/events/68327.json', 'Statsbomb/data/events/267597.json', 'Statsbomb/data/events/69189.json', 'Statsbomb/data/events/266741.json', 'Statsbomb/data/events/70295.json', 'Statsbomb/data/events/266254.json', 'Statsbomb/data/events/69237.json', 'Statsbomb/data/events/69149.json', 'Statsbomb/data/events/265839.json', 'Statsbomb/data/events/266653.json', 'Statsbomb/data/events/69325.json', 'Statsbomb/data/events/69260.json', 'Statsbomb/data/events/69299.json', 'Statsbomb/data/events/69333.json', 'Statsbomb/data/events/69276.json', 'Statsbomb/data/events/70283.json', 'Statsbomb/data/events/303470.json', 'Statsbomb/data/events/266491.json', 'Statsbomb/data/events/9575.json', 'Statsbomb/data/events/15946.json', 'Statsbomb/data/events/69221.json', 'Statsbomb/data/events/266669.json', 'Statsbomb/data/events/69173.json', 'Statsbomb/data/events/68332.json', 'Statsbomb/data/events/266794.json', 'Statsbomb/data/events/68365.json', 'Statsbomb/data/events/70305.json', 'Statsbomb/data/events/16079.json', 'Statsbomb/data/events/16215.json', 'Statsbomb/data/events/70256.json', 'Statsbomb/data/events/267039.json', 'Statsbomb/data/events/68324.json', 'Statsbomb/data/events/9774.json', 'Statsbomb/data/events/69165.json', 'Statsbomb/data/events/266106.json', 'Statsbomb/data/events/68353.json', 'Statsbomb/data/events/70276.json', 'Statsbomb/data/events/69283.json', 'Statsbomb/data/events/69329.json', 'Statsbomb/data/events/266433.json', 'Statsbomb/data/events/265835.json', 'Statsbomb/data/events/9754.json', 'Statsbomb/data/events/69145.json', 'Statsbomb/data/events/70221.json', 'Statsbomb/data/events/266560.json', 'Statsbomb/data/events/69295.json', 'Statsbomb/data/events/69153.json', 'Statsbomb/data/events/9742.json', 'Statsbomb/data/events/267058.json', 'Statsbomb/data/events/266921.json', 'Statsbomb/data/events/303610.json', 'Statsbomb/data/events/303493.json', 'Statsbomb/data/events/9650.json', 'Statsbomb/data/events/70260.json', 'Statsbomb/data/events/69256.json', 'Statsbomb/data/events/267561.json', 'Statsbomb/data/events/70309.json', 'Statsbomb/data/events/69217.json', 'Statsbomb/data/events/266274.json', 'Statsbomb/data/events/267520.json', 'Statsbomb/data/events/69240.json', 'Statsbomb/data/events/69305.json', 'Statsbomb/data/events/69186.json', 'Statsbomb/data/events/267432.json', 'Statsbomb/data/events/69169.json', 'Statsbomb/data/events/68328.json', 'Statsbomb/data/events/69187.json', 'Statsbomb/data/events/267576.json', 'Statsbomb/data/events/68329.json', 'Statsbomb/data/events/69241.json', 'Statsbomb/data/events/69304.json', 'Statsbomb/data/events/267464.json', 'Statsbomb/data/events/69216.json', 'Statsbomb/data/events/9811.json', 'Statsbomb/data/events/16131.json', 'Statsbomb/data/events/303451.json', 'Statsbomb/data/events/70308.json', 'Statsbomb/data/events/266664.json', 'Statsbomb/data/events/16023.json', 'Statsbomb/data/events/69257.json', 'Statsbomb/data/events/69312.json', 'Statsbomb/data/events/267327.json', 'Statsbomb/data/events/266166.json', 'Statsbomb/data/events/68313.json', 'Statsbomb/data/events/266424.json', 'Statsbomb/data/events/266074.json', 'Statsbomb/data/events/69144.json', 'Statsbomb/data/events/70220.json', 'Statsbomb/data/events/303596.json', 'Statsbomb/data/events/16275.json', 'Statsbomb/data/events/69282.json', 'Statsbomb/data/events/69328.json', 'Statsbomb/data/events/303715.json', 'Statsbomb/data/events/266961.json', 'Statsbomb/data/events/70298.json', 'Statsbomb/data/events/68352.json', 'Statsbomb/data/events/70277.json', 'Statsbomb/data/events/267274.json', 'Statsbomb/data/events/9581.json', 'Statsbomb/data/events/69308.json', 'Statsbomb/data/events/266557.json', 'Statsbomb/data/events/68325.json', 'Statsbomb/data/events/69164.json', 'Statsbomb/data/events/266916.json', 'Statsbomb/data/events/266015.json', 'Statsbomb/data/events/267192.json', 'Statsbomb/data/events/266516.json', 'Statsbomb/data/events/266280.json', 'Statsbomb/data/events/68364.json', 'Statsbomb/data/events/70304.json', 'Statsbomb/data/events/303666.json', 'Statsbomb/data/events/16306.json', 'Statsbomb/data/events/69172.json', 'Statsbomb/data/events/68333.json', 'Statsbomb/data/events/266490.json', 'Statsbomb/data/events/9827.json', 'Statsbomb/data/events/69220.json', 'Statsbomb/data/events/70282.json', 'Statsbomb/data/events/68348.json', 'Statsbomb/data/events/265896.json', 'Statsbomb/data/events/266613.json', 'Statsbomb/data/events/69298.json', 'Statsbomb/data/events/69332.json', 'Statsbomb/data/events/9870.json', 'Statsbomb/data/events/69277.json', 'Statsbomb/data/events/69324.json', 'Statsbomb/data/events/9889.json', 'Statsbomb/data/events/69148.json', 'Statsbomb/data/events/303430.json', 'Statsbomb/data/events/69236.json', 'Statsbomb/data/events/266310.json', 'Statsbomb/data/events/70294.json', 'Statsbomb/data/events/266874.json', 'Statsbomb/data/events/266462.json', 'Statsbomb/data/events/267273.json', 'Statsbomb/data/events/303600.json', 'Statsbomb/data/events/70270.json', 'Statsbomb/data/events/69285.json', 'Statsbomb/data/events/266989.json', 'Statsbomb/data/events/9928.json', 'Statsbomb/data/events/69143.json', 'Statsbomb/data/events/69293.json', 'Statsbomb/data/events/68314.json', 'Statsbomb/data/events/69155.json', 'Statsbomb/data/events/266531.json', 'Statsbomb/data/events/70289.json', 'Statsbomb/data/events/69250.json', 'Statsbomb/data/events/9912.json', 'Statsbomb/data/events/303682.json', 'Statsbomb/data/events/16248.json', 'Statsbomb/data/events/69315.json', 'Statsbomb/data/events/267422.json', 'Statsbomb/data/events/69179.json', 'Statsbomb/data/events/267567.json', 'Statsbomb/data/events/69207.json', 'Statsbomb/data/events/16136.json', 'Statsbomb/data/events/9695.json', 'Statsbomb/data/events/16073.json', 'Statsbomb/data/events/69211.json', 'Statsbomb/data/events/16120.json', 'Statsbomb/data/events/69138.json', 'Statsbomb/data/events/69246.json', 'Statsbomb/data/events/69303.json', 'Statsbomb/data/events/69180.json', 'Statsbomb/data/events/267506.json', 'Statsbomb/data/events/70293.json', 'Statsbomb/data/events/68359.json', 'Statsbomb/data/events/15956.json', 'Statsbomb/data/events/69231.json', 'Statsbomb/data/events/267101.json', 'Statsbomb/data/events/16157.json', 'Statsbomb/data/events/69323.json', 'Statsbomb/data/events/69289.json', 'Statsbomb/data/events/9924.json', 'Statsbomb/data/events/69159.json', 'Statsbomb/data/events/68318.json', 'Statsbomb/data/events/303421.json', 'Statsbomb/data/events/69335.json', 'Statsbomb/data/events/69270.json', 'Statsbomb/data/events/69227.json', 'Statsbomb/data/events/68334.json', 'Statsbomb/data/events/16182.json', 'Statsbomb/data/events/303548.json', 'Statsbomb/data/events/69175.json', 'Statsbomb/data/events/267212.json', 'Statsbomb/data/events/69319.json', 'Statsbomb/data/events/266815.json', 'Statsbomb/data/events/267183.json', 'Statsbomb/data/events/70303.json', 'Statsbomb/data/events/68363.json', 'Statsbomb/data/events/16086.json', 'Statsbomb/data/events/16205.json', 'Statsbomb/data/events/68322.json', 'Statsbomb/data/events/16317.json', 'Statsbomb/data/events/266045.json', 'Statsbomb/data/events/9636.json', 'Statsbomb/data/events/69162.json', 'Statsbomb/data/events/68323.json', 'Statsbomb/data/events/9661.json', 'Statsbomb/data/events/9948.json', 'Statsbomb/data/events/267301.json', 'Statsbomb/data/events/70302.json', 'Statsbomb/data/events/303725.json', 'Statsbomb/data/events/69318.json', 'Statsbomb/data/events/266117.json', 'Statsbomb/data/events/9620.json', 'Statsbomb/data/events/68335.json', 'Statsbomb/data/events/16029.json', 'Statsbomb/data/events/9765.json', 'Statsbomb/data/events/69174.json', 'Statsbomb/data/events/69226.json', 'Statsbomb/data/events/70284.json', 'Statsbomb/data/events/303532.json', 'Statsbomb/data/events/266838.json', 'Statsbomb/data/events/69334.json', 'Statsbomb/data/events/267395.json', 'Statsbomb/data/events/69271.json', 'Statsbomb/data/events/69158.json', 'Statsbomb/data/events/266357.json', 'Statsbomb/data/events/68319.json', 'Statsbomb/data/events/69322.json', 'Statsbomb/data/events/69288.json', 'Statsbomb/data/events/9860.json', 'Statsbomb/data/events/69267.json', 'Statsbomb/data/events/9837.json', 'Statsbomb/data/events/69230.json', 'Statsbomb/data/events/303524.json', 'Statsbomb/data/events/70292.json', 'Statsbomb/data/events/68358.json', 'Statsbomb/data/events/266603.json', 'Statsbomb/data/events/69181.json', 'Statsbomb/data/events/266731.json', 'Statsbomb/data/events/69247.json', 'Statsbomb/data/events/69302.json', 'Statsbomb/data/events/266273.json', 'Statsbomb/data/events/69139.json', 'Statsbomb/data/events/303504.json', 'Statsbomb/data/events/9682.json', 'Statsbomb/data/events/15998.json', 'Statsbomb/data/events/69210.json', 'Statsbomb/data/events/266320.json', 'Statsbomb/data/events/266770.json', 'Statsbomb/data/events/69343.json', 'Statsbomb/data/events/303400.json', 'Statsbomb/data/events/69178.json', 'Statsbomb/data/events/68339.json', 'Statsbomb/data/events/69251.json', 'Statsbomb/data/events/69314.json', 'Statsbomb/data/events/70288.json', 'Statsbomb/data/events/68342.json', 'Statsbomb/data/events/266160.json', 'Statsbomb/data/events/68315.json', 'Statsbomb/data/events/69154.json', 'Statsbomb/data/events/69338.json', 'Statsbomb/data/events/16265.json', 'Statsbomb/data/events/69292.json', 'Statsbomb/data/events/69142.json', 'Statsbomb/data/events/266967.json', 'Statsbomb/data/events/267675.json', 'Statsbomb/data/events/68354.json', 'Statsbomb/data/events/70271.json', 'Statsbomb/data/events/266033.json']
485

In [14]:
#create pandas dataframes from the json files containing event data
event_dfs = []

for file in event_lists:
    event_data = pd.read_json(file)
    event_dfs.append(event_data)
    
event_df = pd.concat(event_dfs, ignore_index=True)

In [15]:
event_df.head()

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,team,duration,tactics,related_events,player,position,location,pass,carry,under_pressure,ball_receipt,interception,counterpress,dribble,duel,clearance,foul_won,off_camera,out,foul_committed,ball_recovery,shot,goalkeeper,block,bad_behaviour,substitution,miscontrol,50_50,injury_stoppage,half_start,player_off,half_end
0,1f871f31-7a38-4e3d-a936-cf2397e921f7,1,1,2020-12-13 00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 217, 'name': 'Barcelona'}",0.000000,"{'formation': 433, 'lineup': [{'player': {'id'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,58cbfd8f-7f5d-4ca3-a0cc-e0610f2a2a14,2,1,2020-12-13 00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 214, 'name': 'Espanyol'}",0.000000,"{'formation': 433, 'lineup': [{'player': {'id'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,b48b3dee-38d6-4682-93a9-5e06514d015c,3,1,2020-12-13 00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 217, 'name': 'Barcelona'}",0.000000,NaN,[7d4e60fb-0dac-4a2f-b47a-f7237024cbc8],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7d4e60fb-0dac-4a2f-b47a-f7237024cbc8,4,1,2020-12-13 00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 214, 'name': 'Espanyol'}",0.000000,NaN,[b48b3dee-38d6-4682-93a9-5e06514d015c],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,c6274782-84a9-4ea7-9637-f85dd5f1bbcd,5,1,2020-12-13 00:00:00.103,0,0,"{'id': 30, 'name': 'Pass'}",2,"{'id': 214, 'name': 'Espanyol'}","{'id': 9, 'name': 'From Kick Off'}","{'id': 214, 'name': 'Espanyol'}",3.041801,NaN,[74bb69fe-e633-4938-88cc-c8eefc636843],"{'id': 7781, 'name': 'Felipe Salvador Caicedo ...","{'id': 23, 'name': 'Center Forward'}","[61.0, 41.0]","{'recipient': {'id': 16456, 'name': 'Enzo Pabl...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_shot = event_df.dropna(axis=0, subset=['shot'])

df_shot.head()

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,team,duration,tactics,related_events,player,position,location,pass,carry,under_pressure,ball_receipt,interception,counterpress,dribble,duel,clearance,foul_won,off_camera,out,foul_committed,ball_recovery,shot,goalkeeper,block,bad_behaviour,substitution,miscontrol,50_50,injury_stoppage,half_start,player_off,half_end
341,c49c5561-9253-40a2-a6ce-77f9cd91b828,342,1,2020-12-13 00:07:31.666,7,31,"{'id': 16, 'name': 'Shot'}",15,"{'id': 217, 'name': 'Barcelona'}","{'id': 3, 'name': 'From Free Kick'}","{'id': 217, 'name': 'Barcelona'}",1.351000,NaN,[49cf59f1-641a-40b2-8de0-23275d6a8bb3],"{'id': 5503, 'name': 'Lionel Andrés Messi Cucc...","{'id': 17, 'name': 'Right Wing'}","[94.7, 41.1]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'statsbomb_xg': 0.082942344, 'end_location': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
405,cdf46b32-a097-4c6f-b94e-ec13c6b4c7d0,406,1,2020-12-13 00:09:55.855,9,55,"{'id': 16, 'name': 'Shot'}",19,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 217, 'name': 'Barcelona'}",0.326347,NaN,"[007fb27c-a396-4769-8725-2582ad80dad1, 3aea997...","{'id': 5246, 'name': 'Luis Alberto Suárez Díaz'}","{'id': 23, 'name': 'Center Forward'}","[114.2, 50.8]",NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'statsbomb_xg': 0.16557595, 'end_location': [...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408,883b9214-4798-4690-9f95-1a2025129ff1,409,1,2020-12-13 00:09:57.289,9,57,"{'id': 16, 'name': 'Shot'}",19,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}","{'id': 217, 'name': 'Barcelona'}",0.145100,NaN,[960d1390-eb88-446c-8006-2afb60ecc09a],"{'id': 5503, 'name': 'Lionel Andrés Messi Cucc...","{'id': 17, 'name': 'Right Wing'}","[116.2, 45.7]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'statsbomb_xg': 0.40551847, 'end_location': [...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,abcb0b02-39a1-4275-9ad4-6df0217034ce,496,1,2020-12-13 00:12:25.555,12,25,"{'id': 16, 'name': 'Shot'}",25,"{'id': 217, 'name': 'Barcelona'}","{'id': 3, 'name': 'From Free Kick'}","{'id': 217, 'name': 'Barcelona'}",0.093100,NaN,"[6fd4e858-6941-4807-a305-08f19d81922c, f93e347...","{'id': 4320, 'name': 'Neymar da Silva Santos J...","{'id': 21, 'name': 'Left Wing'}","[107.1, 35.4]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'statsbomb_xg': 0.11238169, 'end_location': [...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
572,553faf7a-bfee-4c1a-a4cb-3982394c8c71,573,1,2020-12-13 00:15:15.317,15,15,"{'id': 16, 'name': 'Shot'}",32,"{'id': 217, 'name': 'Barcelona'}","{'id': 3, 'name': 'From Free Kick'}","{'id': 217, 'name': 'Barcelona'}",1.226400,NaN,[7cef6fc4-ab7c-4831-9fb9-49a0fbd96133],"{'id': 5503, 'name': 'Lionel Andrés Messi Cucc...","{'id': 17, 'name': 'Right Wing'}","[96.3, 24.5]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'statsbomb_xg': 0.040308565000000005, 'end_lo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_location = df_shot['location']

In [17]:
df_shot_modified = pd.DataFrame(df_shot['shot'].tolist())

In [18]:
df_shot_modified.head()

,statsbomb_xg,end_location,technique,body_part,type,outcome,freeze_frame,key_pass_id,first_time,one_on_one,aerial_won,open_goal,deflected,saved_to_post,saved_off_target,redirect,follows_dribble
0,0.082942,"[120.0, 42.8, 2.1]","{'id': 93, 'name': 'Normal'}","{'id': 38, 'name': 'Left Foot'}","{'id': 62, 'name': 'Free Kick'}","{'id': 97, 'name': 'Goal'}","[{'location': [93.2, 52.0], 'player': {'id': 4...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.165576,"[118.7, 43.9, 0.4]","{'id': 93, 'name': 'Normal'}","{'id': 40, 'name': 'Right Foot'}","{'id': 87, 'name': 'Open Play'}","{'id': 100, 'name': 'Saved'}","[{'location': [118.8, 43.4], 'player': {'id': ...",9d871ecc-76bc-4b2d-a815-1c99df5e1ada,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.405518,"[117.7, 43.6, 0.2]","{'id': 93, 'name': 'Normal'}","{'id': 40, 'name': 'Right Foot'}","{'id': 87, 'name': 'Open Play'}","{'id': 100, 'name': 'Saved'}","[{'location': [118.0, 43.6], 'player': {'id': ...",NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.112382,"[109.4, 36.5]","{'id': 93, 'name': 'Normal'}","{'id': 40, 'name': 'Right Foot'}","{'id': 87, 'name': 'Open Play'}","{'id': 96, 'name': 'Blocked'}","[{'location': [118.2, 39.0], 'player': {'id': ...",bec886cf-1162-49ab-af1e-7d798eb14e40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.040309,"[120.0, 36.4, 4.5]","{'id': 93, 'name': 'Normal'}","{'id': 38, 'name': 'Left Foot'}","{'id': 62, 'name': 'Free Kick'}","{'id': 98, 'name': 'Off T'}","[{'location': [94.5, 35.5], 'player': {'id': 5...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df_dict = df_shot_modified[['technique', 'body_part', 'type', 'outcome']]

In [48]:
shot_data = df_shot_modified.drop(['technique', 'body_part', 'type', 'outcome', 'end_location', 'freeze_frame', 'key_pass_id'], axis=1)

In [22]:
df_dict_technique = pd.DataFrame(df_dict['technique'].tolist())

In [23]:
df_dict_technique.head()

   id    name
0  93  Normal
1  93  Normal
2  93  Normal
3  93  Normal
4  93  Normal

In [73]:
df_technique = df_dict_technique.drop('id', axis=1)
df_technique.rename(columns={"name":"technique"}, inplace=True)
print(df_technique.head())
print(len(df_technique))

  technique
0    Normal
1    Normal
2    Normal
3    Normal
4    Normal
12003

In [25]:
df_dict_body_part = pd.DataFrame(df_dict['body_part'].tolist())

In [26]:
df_dict_body_part.head()

   id        name
0  38   Left Foot
1  40  Right Foot
2  40  Right Foot
3  40  Right Foot
4  38   Left Foot

In [72]:
df_body_part = df_dict_body_part.drop('id', axis=1)
df_body_part.rename(columns={"name":"body_part"}, inplace=True)
print(df_body_part.head())
print(len(df_body_part))

    body_part
0   Left Foot
1  Right Foot
2  Right Foot
3  Right Foot
4   Left Foot
12003

In [28]:
df_dict_type = pd.DataFrame(df_dict['type'].tolist())

In [29]:
df_dict_type.head()

   id       name
0  62  Free Kick
1  87  Open Play
2  87  Open Play
3  87  Open Play
4  62  Free Kick

In [74]:
df_type = df_dict_type.drop('id', axis=1)
df_type.rename(columns={"name":"type"}, inplace=True)
print(df_type.head())
print(len(df_type))

        type
0  Free Kick
1  Open Play
2  Open Play
3  Open Play
4  Free Kick
12003

In [31]:
df_dict_outcome = pd.DataFrame(df_dict['outcome'].tolist())

In [32]:
df_dict_outcome.head()

    id     name
0   97     Goal
1  100    Saved
2  100    Saved
3   96  Blocked
4   98    Off T

In [75]:
df_outcome = df_dict_outcome.drop('id', axis=1)
df_outcome.rename(columns={"name":"outcome"}, inplace=True)
print(df_outcome.head())
print(len(df_outcome))

   outcome
0     Goal
1    Saved
2    Saved
3  Blocked
4    Off T
12003

In [76]:
df_shot_final = pd.concat([shot_data, df_technique, df_body_part, df_type, df_outcome, df_location.reset_index(drop=True)], axis=1)

In [77]:
df_shot_final.head()

,statsbomb_xg,first_time,one_on_one,aerial_won,open_goal,deflected,saved_to_post,saved_off_target,redirect,follows_dribble,technique,body_part,type,outcome,location
0,0.082942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Left Foot,Free Kick,Goal,"[94.7, 41.1]"
1,0.165576,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Right Foot,Open Play,Saved,"[114.2, 50.8]"
2,0.405518,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Right Foot,Open Play,Saved,"[116.2, 45.7]"
3,0.112382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Right Foot,Open Play,Blocked,"[107.1, 35.4]"
4,0.040309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Left Foot,Free Kick,Off T,"[96.3, 24.5]"

In [78]:
df_shot_final.dropna(axis=0, subset=['location'])

,statsbomb_xg,first_time,one_on_one,aerial_won,open_goal,deflected,saved_to_post,saved_off_target,redirect,follows_dribble,technique,body_part,type,outcome,location
0,0.082942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Left Foot,Free Kick,Goal,"[94.7, 41.1]"
1,0.165576,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Right Foot,Open Play,Saved,"[114.2, 50.8]"
2,0.405518,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Right Foot,Open Play,Saved,"[116.2, 45.7]"
3,0.112382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Right Foot,Open Play,Blocked,"[107.1, 35.4]"
4,0.040309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Left Foot,Free Kick,Off T,"[96.3, 24.5]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11998,0.082145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Right Foot,Open Play,Blocked,"[104.1, 28.9]"
11999,0.085953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Head,Open Play,Off T,"[108.1, 37.6]"
12000,0.192398,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Half Volley,Right Foot,Open Play,Blocked,"[109.6, 40.8]"
12001,0.014248,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Left Foot,Open Play,Saved,"[92.0, 49.1]"
12002,0.760000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,Left Foot,Penalty,Goal,"[107.9, 40.1]"

In [79]:
df_shot_final.to_pickle("ExG Shot Data")